[package]
name = "crowser"
version = "0.1.0"
edition = "2021"
rust-version = "1.70.0"

# This is a library
[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
include_dir = "0.7.4"
lazy_static = "1.5.0"
mime_guess = "2.0.5"
phf = { version = "0.11.2", features = ["macros"] }
shared_child = "1.0.1"
signal-hook = "0.3.17"
tiny_http = "0.12.0"

[target.'cfg(linux)'.dependencies]
which = "6.0.2"

[build-dependencies]
serde = "1.0.205"
serde_json = "1.0.122"
