name: Lint

on:
  push:
    paths:
      - '.github/workflows/check.yml'
      - 'Cargo.toml'
      - 'rustfmt.toml'
      - 'src/**/*'
  pull_request:
    paths:
      - '.github/workflows/check.yml'
      - 'Cargo.toml'
      - 'rustfmt.toml'
      - 'src/**/*'

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1.8
        with:
          components: rustfmt

      - name: Cargo format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path ./Cargo.toml --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1.8
        with:
          components: clippy

      - name: Cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --manifest-path ./Cargo.toml --all -- --deny warnings

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1.8

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Cargo audit
        uses: actions-rs/cargo@v1
        with:
          command: audit
