name: Publish

on:
  push:
    paths:
      - '.github/workflows/publish.yml'
      - 'Cargo.toml'
      - 'src/**/*'
concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1.8
      
      - name: Cargo publish
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --manifest-path ./Cargo.toml --all-features --token ${{ secrets.CARGO_TOKEN }}